[project]
name = "businesspolicy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.7",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]
